# Generated by Django 5.1.2 on 2024-11-04 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.supplier'),
        ),
    ]
